name: C/C++ CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        cd test
        make
    - name: test
      run: ./test/run_test.sh

